// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbGnuvrzTgaCycrlMOrorgyGkjNvuDs00',
    appId: '1:255844066682:web:33caa351644a0cc2c962c3',
    messagingSenderId: '255844066682',
    projectId: 'ciftci-flutter-projesi-974aa',
    authDomain: 'ciftci-flutter-projesi-974aa.firebaseapp.com',
    databaseURL:
        'https://ciftci-flutter-projesi-974aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ciftci-flutter-projesi-974aa.appspot.com',
    measurementId: 'G-S5QMVELM4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC91opyGctlfhP4silHJUdUJiU4nPdddMQ',
    appId: '1:255844066682:android:7b658e12542b5f4ec962c3',
    messagingSenderId: '255844066682',
    projectId: 'ciftci-flutter-projesi-974aa',
    databaseURL:
        'https://ciftci-flutter-projesi-974aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ciftci-flutter-projesi-974aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX-dB56WaLDUfcNphbSvoi4_Yj85pPNqk',
    appId: '1:255844066682:ios:537350aff6b81430c962c3',
    messagingSenderId: '255844066682',
    projectId: 'ciftci-flutter-projesi-974aa',
    databaseURL:
        'https://ciftci-flutter-projesi-974aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ciftci-flutter-projesi-974aa.appspot.com',
    iosClientId:
        '255844066682-3nop1thicoke0f77eumq0lieslog3djc.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCiftcim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX-dB56WaLDUfcNphbSvoi4_Yj85pPNqk',
    appId: '1:255844066682:ios:537350aff6b81430c962c3',
    messagingSenderId: '255844066682',
    projectId: 'ciftci-flutter-projesi-974aa',
    databaseURL:
        'https://ciftci-flutter-projesi-974aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ciftci-flutter-projesi-974aa.appspot.com',
    iosClientId:
        '255844066682-3nop1thicoke0f77eumq0lieslog3djc.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCiftcim',
  );
}
